@startuml
left to right direction
actor "User" as usr
rectangle "Heimdall Universe" {
  usecase "List Kubeconfigs" as UC1
  usecase "Select a Kubeconfig" as UC2
  usecase "Add a Kubeconfig" as UC3
}
usr --> UC1
usr --> UC2
usr --> UC3
@enduml
